trigger:
- master

parameters:
  - name: helloString
    type: string
    default: Hello World

stages:
  - stage: printhello
    jobs:
      - job: printhelloworld
        steps:
          - script: echo ${{ parameters.hellostring }}
            displayName: 'Hello World Test'