trigger:
- master

parameters:
  - name: helloString
    type: string
    default: Hello World

stages:
  - stage: printhello
    jobs:
      - job: printhelloworld
        steps:
          - script: 'echo ${{ parameters.hellostring }}'
            displayName: 'Hello World Test'
  - stage: finish
    jobs:
      - job: printfinish
        steps:
          - script: 'echo "Hello World is finished printing"'
            displayName: 'Finished'